#name of our pipeline
name: Cucumber Pipeline

#trigger pipeline when someone push to the main branch and when someone do a pull request from the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#forcing the script to run on “Node.js 24” as per the warning under the Annotations
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

#creating jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven

#running the tests in the pipeline
      - name: Build and Run Tests
        run: mvn clean test -Dheadless=true

#uploading report to the pipeline
      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Group-report
          path: test-output/



